package org.bearo

enum class ConfigLayer(val priority: Int) {
    COMMAND_LINE_ARGS(0),
    SYSTEM_PROPERTIES(1),
    ENVIRONMENT_VARIABLES(2),
    LOCAL_CONFIG_JSON(3),
    LOCAL_CONFIG_TOML(4),
    GLOBAL_CONFIG_JSON(5),
    GLOBAL_CONFIG_TOML(6),
    CLASSPATH_CONFIG_JSON(7),
    CLASSPATH_CONFIG_TOML(8),
    DEFAULTS_JSON(9),
    DEFAULTS_TOML(10),
    HARDCODED_DEFAULTS(11),
}